---
title: "Relatedness.Phmi"
author: "Akira Hirao"
date: "`r Sys.Date()`"
output: 
  md_document:
    toc: true
    variant: markdown_github
  html_document:
    toc: true
---

# Analysing pairwise relatedness with using the R package "related" 

## Loading the packages

```{r message = FALSE, warning = FALSE, echo = TRUE}
# Loading packages
library(related) #Pew et al (2015) Mol Ecol Res | https://doi.org/10.1111/1755-0998.12323
library(ggplot2)
library(adegenet) #handling of genind object
library(poppr) #handling of genclone object
library(stringr)
```

## Loading the dataset

```{r message = FALSE, warning = FALSE, echo = TRUE}
#initializing
rm(list = ls())

# Loading data set
nameko.raw <- read.csv("MLG_Pmicro_124samples.csv",header=T)

# define locus name
locus.names <- unique(str_sub(colnames(nameko.raw)[-c(1:4)],end=-2))
no.locus <- length(locus.names)

# Convert to 6-digit-numeric coded-genotype
nameko.6_digit.genotype.raw = data.frame()
nameko.6_digit.genotype.raw = data.frame(nameko.raw[,c(1:4)])
for (i in 1:no.locus){
  allele.A.position = 3 + i*2
  allele.B.position = 4 + i*2
  target.loci = locus.names[i]
  nameko.6_digit.genotype.raw = data.frame(nameko.6_digit.genotype.raw, target.loci = paste(formatC(nameko.raw[,allele.A.position],width=3, flag="0"),formatC(nameko.raw[,allele.B.position],width=3, flag="0"),sep=""))
}
colnames(nameko.6_digit.genotype.raw)[-c(1:4)] <- locus.names


#filtering out the sample "K23" because of missing alleles as expressed "NA"
nameko.6_digit.genotype  <- na.omit(nameko.6_digit.genotype.raw)

# Convert to genind object
nameko.SSR.genind <- df2genind(nameko.6_digit.genotype[,-c(1:4)],ploidy=2,ncode=3,ind.name=nameko.6_digit.genotype$ID,pop=nameko.6_digit.genotype$Category)
strata(nameko.SSR.genind) <- data.frame(nameko.6_digit.genotype[,c(2:3)])

# Convert to genclone object
nameko.SSR.genclone <- as.genclone(nameko.SSR.genind)

# Clone correction
nameko.SSR.MLG.genind <- clonecorrect(nameko.SSR.genind)

nameko.genotype.MLG <- genind2df(nameko.SSR.MLG.genind, usepop = FALSE, oneColPerAll = TRUE)
nameko.genotype.MLG <- data.frame(ID=rownames(nameko.genotype.MLG),nameko.genotype.MLG)

MLG.ID.No.wild <- which(nameko.SSR.MLG.genind@strata$Category=="Wild")
MLG.ID.No.cultivar <- which(nameko.SSR.MLG.genind@strata$Category=="Cultivar")
MLG.ID.No.cultivar.sawdust <- which(nameko.SSR.MLG.genind@strata$Source=="Cultivar.sawdust.JPN")
MLG.ID.No.cultivar.others <- setdiff(MLG.ID.No.cultivar, MLG.ID.No.cultivar.sawdust)

nameko.genotype.MLG.wild <- nameko.genotype.MLG[MLG.ID.No.wild,]
nameko.genotype.MLG.cultivar <- nameko.genotype.MLG[MLG.ID.No.cultivar,]
nameko.genotype.MLG.cultivar.sawdust <- nameko.genotype.MLG[MLG.ID.No.cultivar.sawdust,]
nameko.genotype.MLG.cultivar.others <- nameko.genotype.MLG[MLG.ID.No.cultivar.others,]

MLG.ID.wild <- nameko.genotype.MLG.wild$ID
MLG.ID.cultivar <- nameko.genotype.MLG.cultivar$ID
MLG.ID.cultivar.sawdust <- nameko.genotype.MLG.cultivar.sawdust$ID
MLG.ID.cultivar.others <- setdiff(MLG.ID.cultivar, MLG.ID.cultivar.sawdust)

# write out text file to apply the pakacates "related"
write.table(nameko.genotype.MLG, "nameko.MLG.txt", quote=F,row.names=F,col.names=F, append=F)
```

## Estimating pairwise relatedness

```{r message = FALSE, warning = FALSE, echo = TRUE}
## Load the data file from the above text file.
nameko.Genotype <- readgenotypedata("nameko.MLG.txt")

## Run coancestry function in the packages "related"
related.run.output <- coancestry(nameko.Genotype$gdata, dyadml=1, trioml=1, lynchli=1, lynchrd=1, quellergt=1, ritland =1, wang=1)
```

## Comparing Relatedness Estimators

```{r message = FALSE, warning = FALSE, echo = TRUE}
compareestimators(nameko.Genotype, 100)
```

## Conducting simulations 

```{r message = FALSE, warning = FALSE, echo = TRUE}
sim <- familysim(nameko.Genotype$freqs, 100)
output <- coancestry(sim, quellergt=1)
simrel <- cleanuprvals(output$relatedness, 100)
relvalues <- simrel[, 10]

#label
label1 <- rep("PO", 100)
label2 <- rep("Full", 100)
label3 <- rep("Half", 100)
label4 <- rep("Unrelated", 100)
labels <- c(label1, label2, label3, label4)

Relationship <- labels
newdata <- as.data.frame(cbind(Relationship, relvalues))
newdata$relvalues <- as.numeric(as.character(newdata$relvalues))
qplot(relvalues, ..density.., data=newdata, geom="density", colour=as.factor(Relationship), xlab="Relatedness Value", ylab="Density")
```

## Plotting pairwise relatedness

```{r message = FALSE, warning = FALSE, echo = TRUE}
## The Queller & Goodnight estimator (1989) of relatedness was chosen to applied for the following analyses
relatedness.out <- data.frame(ind1.id=related.run.output$related$ind1.id, ind2.id=related.run.output$related$ind2.id, relatedness=related.run.output$related$quellergt)

relatedness.out.wild <- subset(relatedness.out,ind1.id %in% MLG.ID.wild & ind2.id %in% MLG.ID.wild)
no.wild.pair <- nrow(relatedness.out.wild)
relatedness.out.wild <- data.frame(relatedness.out.wild, Within=rep("Wild",no.wild.pair))

relatedness.out.cultivar <- subset(relatedness.out,ind1.id %in% MLG.ID.cultivar & ind2.id %in% MLG.ID.cultivar)
no.cultivar.pair <- nrow(relatedness.out.cultivar)
relatedness.out.cultivar <- data.frame(relatedness.out.cultivar, Within=rep("Cultivar",no.cultivar.pair))

relatedness.out.cultivar.sawdust <- subset(relatedness.out,ind1.id %in% MLG.ID.cultivar.sawdust & ind2.id %in% MLG.ID.cultivar.sawdust)
no.cultivar.sawdust.pair <- nrow(relatedness.out.cultivar.sawdust)
relatedness.out.cultivar.sawdust <- data.frame(relatedness.out.cultivar.sawdust, Within=rep("Cultivar.sawdust",no.cultivar.sawdust.pair))

relatedness.out.cultivar.others <- subset(relatedness.out,ind1.id %in% MLG.ID.cultivar.others & ind2.id %in% MLG.ID.cultivar.others)
no.cultivar.others.pair <- nrow(relatedness.out.cultivar.others)

relatedness.out.cultivar.others <- data.frame(relatedness.out.cultivar.others, Within=rep("Cultivar.others",no.cultivar.others.pair))

relatedness.out.within <- rbind(relatedness.out.wild,relatedness.out.cultivar.sawdust,relatedness.out.cultivar.others)

relatedness.out.within.wild.vs.cultivar.others <- rbind(relatedness.out.wild,relatedness.out.cultivar.others)

relatedness.out.within.wild.vs.cultivar.sawdust <- rbind(relatedness.out.wild,relatedness.out.cultivar.sawdust)
relatedness.out.within.cultivar.others.vs.cultivar.sawdust <- rbind(relatedness.out.cultivar.others,relatedness.out.cultivar.sawdust)

cat("relatedness within wild: mean, SD\n")
print(mean(relatedness.out.wild$relatedness))
print(sd(relatedness.out.wild$relatedness))

cat("relatedness within cultivar.sawdust: mean, SD\n")
print(mean(relatedness.out.cultivar.sawdust$relatedness))
print(sd(relatedness.out.cultivar.sawdust$relatedness))

cat("relatedness within cultivar.others: mean, SD\n")
print(mean(relatedness.out.cultivar.others$relatedness))
print(sd(relatedness.out.cultivar.others$relatedness))

relatedness.out.N127.N2 <- subset(relatedness.out,ind1.id %in% "Tohoku-N127" & ind2.id %in% "Fukushima-N2")
cat("relatedness between N127 and Fukushima-N2\n")
print(relatedness.out.N127.N2$relatedness)

p.boxplot <- ggplot(relatedness.out.within, aes(x=Within,y=relatedness)) + geom_boxplot() + xlab("") + ylab("Relatedness")

p.boxplot
```

```{r message = FALSE, warning = FALSE, echo = TRUE}
## permutation test
no.permutation <- 1000
permutation.test <- function(treatment, outcome, n){
  distribution=c()
  obs <- diff(tapply(outcome,treatment,mean))
  for(i in 1:n){
    distribution[i]=diff(by(outcome, sample(treatment, length(treatment), FALSE), mean))
  }
  result=sum(abs(distribution) >= abs(obs))/(n)
  return(list(obs, result, distribution))
  }

# wild vs cultivar.others
wild.vs.cultivar.others.permu.out <- permutation.test(relatedness.out.within.wild.vs.cultivar.others$Within, relatedness.out.within.wild.vs.cultivar.others$relatedness, no.permutation)

# wild vs cultivar.sawdust
wild.vs.cultivar.sawdust.permu.out <- permutation.test(relatedness.out.within.wild.vs.cultivar.sawdust$Within, relatedness.out.within.wild.vs.cultivar.sawdust$relatedness, no.permutation)

# cultivar.others vs cultivar.sawdust
cultivar.others.vs.cultivar.sawdust.permu.out <- permutation.test(relatedness.out.within.cultivar.others.vs.cultivar.sawdust$Within, relatedness.out.within.cultivar.others.vs.cultivar.sawdust$relatedness, no.permutation)

# print out P value
cat("P value: wild vs cultivar.others\n")
print(format(wild.vs.cultivar.others.permu.out[[2]]),digits=3)

cat("P value: wild vs cultivar.sawdust\n")
print(format(wild.vs.cultivar.sawdust.permu.out[[2]]),digits=3)

cat("P value: cultivar.others vs cultivar.sawdust\n")
print(format(cultivar.others.vs.cultivar.sawdust.permu.out[[2]]),digits=3)
```